name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk wget unzip zip squashfs-tools git python3-dev build-essential
        pip install python-for-android cython
        
    - name: Build APK with p4a
      run: |
        p4a apk --private . --package=com.facialattendance --name="Facial Recognition Attendance" --version=1.0 --bootstrap=sdl2 --requirements=python3,kivy,opencv-python,numpy --android-api=29
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: *.apk
